export const germanyCities = [
    "Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt", "Stuttgart", "Düsseldorf", "Dortmund",
    "Essen", "Leipzig", "Bremen", "Dresden", "Hanover", "Nuremberg", "Duisburg", "Bochum", "Wuppertal",
    "Bielefeld", "Bonn", "Münster", "Karlsruhe", "Mannheim", "Augsburg", "Wiesbaden", "Gelsenkirchen",
    "Mönchengladbach", "Braunschweig", "Chemnitz", "Kiel", "Aachen", "Halle", "Magdeburg", "Freiburg",
    "Krefeld", "Lübeck", "Oberhausen", "Erfurt", "Mainz", "Rostock", "Kassel", "Hagen", "Saarbrücken",
    "Hamm", "Potsdam", "Mülheim", "Ludwigshafen", "Oldenburg", "Leverkusen", "Osnabrück", "Solingen",
    "Heidelberg", "Herne", "Neuss", "Darmstadt", "Paderborn", "Regensburg", "Ingolstadt", "Würzburg",
    "Wolfsburg", "Offenbach", "Ulm", "Heilbronn", "Pforzheim", "Göttingen", "Bottrop", "Trier", "Recklinghausen",
    "Reutlingen", "Bremerhaven", "Koblenz", "Bergisch Gladbach", "Jena", "Remscheid", "Erlangen", "Moers",
    "Siegen", "Hildesheim", "Salzgitter", "Cottbus", "Kaiserslautern", "Gütersloh", "Schwerin", "Witten",
    "Gera", "Iserlohn", "Ludwigsburg", "Zwickau", "Düren", "Esslingen", "Ratingen", "Marl", "Lünen",
    "Velbert", "Hanau", "Villingen-Schwenningen", "Konstanz", "Minden", "Dessau", "Worms", "Neumünster",
    "Norderstedt", "Delmenhorst", "Tübingen", "Fulda", "Wilhelmshaven", "Viersen", "Gladbeck", "Dorsten",
    "Rheine", "Detmold", "Troisdorf", "Marburg", "Bayreuth", "Lüneburg", "Landshut", "Aschaffenburg",
    "Aalen", "Bamberg", "Brandenburg", "Lüdenscheid", "Bocholt", "Dinslaken", "Emden", "Neubrandenburg",
    "Rüsselsheim", "Passau", "Castrop-Rauxel", "Nürtingen", "Görlitz", "Herten", "Wesel", "Grevenbroich",
    "Frechen", "Neunkirchen", "Stolberg", "Bünde", "Baden-Baden", "Sankt Augustin", "Wesel", "Grevenbroich",
    "Herten", "Rheda-Wiedenbrück", "Hattingen", "Görlitz", "Langenfeld", "Greifswald", "Bad Homburg",
    "Meerbusch", "Oranienburg", "Schwäbisch Gmünd", "Hürth", "Neu-Ulm", "Weimar", "Hof", "Göppingen",
    "Homburg", "Landau", "Bergheim", "Biberach", "Heidenheim", "Alsdorf", "Kaufbeuren", "Sankt Ingbert",
    "Speyer", "Frankfurt (Oder)", "Kempten", "Dachau", "Erkrath", "Lohmar", "Bad Salzuflen", "Kleve",
    "Lingen", "Bietigheim-Bissingen", "Tübingen", "Deggendorf", "Straubing", "Bitterfeld-Wolfen",
    "Dülmen", "Wetzlar", "Eisenach", "Memmingen", "Schwabach", "Hennef", "Bad Oeynhausen", "Gladbeck",
    "Troisdorf", "Gotha", "Sindelfingen", "Bad Kreuznach", "Neu-Isenburg", "Backnang", "Bad Kreuznach",
    "Minden", "Schwäbisch Hall", "Elmshorn", "Hameln", "Leinfelden-Echterdingen", "Garmisch-Partenkirchen",
    "Wunstorf", "Eberswalde", "Pulheim", "Erkrath", "Schorndorf", "Wismar", "Höxter", "Borken", "Bornheim",
    "Rosenheim", "Reinbek", "Borken", "Rheda-Wiedenbrück", "Kornwestheim", "Meppen", "Nordhorn", "Greiz",
    "Landsberg", "Freudenstadt", "Pirna", "Winnenden", "Riesa", "Varel", "Lübbecke", "Lehrte", "Viersen",
    "Selm", "Uetze", "Falkensee", "Bad Vilbel", "Rastatt", "Rottweil", "Schwerte", "Schwäbisch Hall",
    "Mühlhausen", "Dietzenbach", "Lingen", "Suhl", "Griesheim", "Bünde", "Harsewinkel", "Wedel",
    "Ibbenbüren", "Haan", "Kevelaer", "Seelze", "Neubrandenburg", "Erkelenz", "Waiblingen", "Heiligenhaus",
    "Ilmenau", "Wetzlar", "Forchheim", "Waldkraiburg", "Würselen", "Pfungstadt", "Eschweiler", "Wernigerode",
    "Freital", "Rheinfelden", "Hohen Neuendorf", "Kamen", "Sondershausen", "Weinheim", "Lünen",
    "Coburg", "Goslar", "Kitzingen", "Bad Mergentheim", "Hofheim", "Dülmen", "Frechen", "Friedberg",
    "Lübbecke", "Erding", "Meinerzhagen", "Gardelegen", "Nagold", "Brühl", "Kaarst", "Radevormwald",
    "Germering", "Ronnenberg", "Waldkirch", "Laatzen", "Neukirchen-Vluyn", "Kleinmachnow", "Versmold",
    "Calw", "Rottenburg", "Geislingen", "Bad Rappenau", "Olching", "Neu-Ulm", "Rodgau", "Völklingen",
    "Plauen", "Borken", "Bensheim", "Rödermark", "Schmallenberg", "Güstrow", "Bad Hersfeld", "Bad Aibling",
    "Rotenburg", "Delbrück", "Bad Honnef", "Bad Wildungen", "Grimma", "Butzbach", "Leinfelden-Echterdingen",
    "Worms", "Gevelsberg", "Heilbad Heiligenstadt", "Schwäbisch Gmünd", "Kamen", "Hückelhoven", "Büren",
    "Andernach", "Mendig", "Warendorf", "Grünstadt", "Gescher", "Bad Doberan", "Quedlinburg", "Wesseling",
    "Fellbach", "Dachau", "Langen", "Eberswalde", "Weingarten", "Büren", "Borken", "Butzbach", "Calw",
    "Rotenburg", "Ahrensburg", "Norderstedt", "Weingarten", "Ilmenau", "Rastatt", "Lengerich", "Brilon",
    "Osterholz-Scharmbeck", "Wermelskirchen", "Radolfzell", "Nordenham", "Landau", "Kamen", "Steinfurt",
    "Geldern", "Eitorf", "Schifferstadt", "Buchholz", "Kehl", "Nördlingen", "Donauwörth", "Crailsheim",
    "Ehingen", "Geretsried", "Künzelsau", "Lindau", "Deggendorf", "Oerlinghausen", "Radebeul", "Hof",
    "Kelheim", "Bietigheim-Bissingen", "Achern", "Dietzenbach", "Löhne", "Wittmund", "Neuötting",
    "Albstadt", "Garmisch-Partenkirchen", "Schwabmünchen", "Öhringen", "Wolfratshausen", "Burgdorf",
    "Oberndorf", "Neukirchen", "Gera", "Erlensee", "Rostock", "Gummersbach"
]


